// src/UIs/bff/reactjs/src/containers/Home/Home.tsx
import React from "react";
import logo from "../../logo.svg";
import Timer from "../../components/Timer/Timer";

import "./Home.css";

function Home() {
  const date = new Date();
  return (
    <div className="card">
      <div className="card-header">
        Welcome ClassifiedAds React version: {React.version}
        <div style={{ float: "right", color: "green" }}>
          <Timer />
        </div>
      </div>
      <div className="card-body">
        <div className="container-fluid">
          <div className="text-center">
            <img
              src={logo}
              className="img-responsive center-block"
              style={{ maxHeight: "300px", paddingBottom: "10px" }}
            />
          </div>

          <div className="text-center">Developed by:</div>
          <div className="text-center">
            <h3>Emerson Costa</h3>
          </div>

          <div className="text-center">@brightsmile</div>
          <div className="text-center">
            <a href="https://github.com/EmersonCosta915/Practical.CleanArchitecture">
              Practical.CleanArchitecture
            </a>
          </div>
          <div className="text-center">
            <strong>react v{React.version}</strong>
          </div>
          <div className="text-center">{date.toLocaleDateString()}</div>
        </div>
      </div>
    </div>
  );
}

export default Home;

// src/UIs/vuejs/src/views/Home.vue
<template>
  <div class="card">
    <div class="card-header">{{ appendVersion(pageTitle) }}
      <div style="float: right;color: green">
        <app-timer></app-timer>
      </div>
    </div>
    <div class="card-body">
      <div class="container-fluid">
        <div class="text-center">
          <img src="../assets/logo.png" class="img-responsive center-block"
            style="max-height:300px;padding-bottom:10px" />
        </div>

        <div class="text-center">Developed by:</div>
        <div class="text-center">
          <h3>Emerson Costa</h3>
        </div>
        <div class="text-center">@brightsmile</div>
        <div class="text-center">
          <a href="https://github.com/EmersonCosta915/Practical.CleanArchitecture">Practical.CleanArchitecture</a>
        </div>
        <div class="text-center">
          <strong>vuejs v{{ version }}</strong>
        </div>
        <div class="text-center">{{ appendCurrentDateTime("") }}</div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, version } from "vue";

import Timer from "../components/Timer.vue"

export default defineComponent({
  name: "Home" as string,
  data() {
    return {
      pageTitle: "Welcome ClassifiedAds Vue" as string,
      version: version
    };
  },
  components: {
    appTimer: Timer
  },
  methods: {
    appendVersion: function (value: string) {
      return value + " " + version;
    },
    appendCurrentDateTime: function (value: string) {
      return value + " " + new Date();
    }
  }
});
</script>
